-- MySQL Script generated by MySQL Workbench
-- mié 06 nov 2019 13:25:27 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table VIVERO
-- -----------------------------------------------------
CREATE TABLE  VIVERO (
  Coordenadas INT NOT NULL,
  Localizacion VARCHAR(45) NULL,
  PRIMARY KEY (Coordenadas))
;


-- -----------------------------------------------------
-- Table ZONA
-- -----------------------------------------------------
CREATE TABLE  ZONA (
  Nombre VARCHAR(45) NOT NULL,
  Coordenadas INT NULL,
  PRIMARY KEY (Nombre),
  CONSTRAINT Coordenadas
    FOREIGN KEY (Coordenadas)
    REFERENCES VIVERO (Coordenadas)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table PRODUCTO
-- -----------------------------------------------------
CREATE TABLE  PRODUCTO (
  Codigo INT NOT NULL,
  Stock INT NULL,
  Precio INT NULL,
  PRIMARY KEY (Codigo))
;


-- -----------------------------------------------------
-- Table UBICA
-- -----------------------------------------------------
CREATE TABLE  UBICA (
  Nombre VARCHAR(45) NOT NULL,
  Codigo INT NOT NULL,
  Coordenadas INT NOT NULL,
  PRIMARY KEY (Nombre, Codigo, Coordenadas),
  CONSTRAINT Nombre
    FOREIGN KEY (Nombre,Coordenadas)
    REFERENCES ZONA (Nombre, Coordenadas)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT Codigo
    FOREIGN KEY (Codigo)
    REFERENCES PRODUCTO (Codigo)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table CLIENTE
-- -----------------------------------------------------
CREATE TABLE  CLIENTE (
  dni VARCHAR(45) NOT NULL,
  Bonificacion INT NULL,
  Total_mensual INT NULL,
  PRIMARY KEY (dni))
;


-- -----------------------------------------------------
-- Table EMPLEADO
-- -----------------------------------------------------
CREATE TABLE  EMPLEADO (
  dni VARCHAR(45) NOT NULL,
  Sueldo INT NULL,
  css INT NULL,
  Antiguedad INT NULL,
  Nombre VARCHAR(45) NULL,
  Coordenadas INT NULL,
  PRIMARY KEY (dni),
  CONSTRAINT Nombre
    FOREIGN KEY (Nombre,Coordenadas)
    REFERENCES ZONA (Nombre, Coordenadas)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table EM_CLI_PRO
-- -----------------------------------------------------
CREATE TABLE  EM_CLI_PRO (
  dni_cli VARCHAR(45) NOT NULL,
  Codigo INT NOT NULL,
  Cantidad INT NULL,
  Fecha DATE NOT NULL,
  dni_em VARCHAR(45) NOT NULL,
  PRIMARY KEY (dni_cli, Codigo, Fecha, dni_em),
  CONSTRAINT dni_cli
    FOREIGN KEY (dni_cli)
    REFERENCES CLIENTE (dni)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT dni_em
    FOREIGN KEY (dni_em)
    REFERENCES EMPLEADO (dni)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT Codigo
    FOREIGN KEY (Codigo)
    REFERENCES PRODUCTO (Codigo)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
;

